<?php require_once 'template/admin_header.phtml';
?>

<link rel="stylesheet" href="bootstrap/css/signin.css"> 

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Just a temp page to enter Admin Details. Not to be LIVE!!</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="admin_superuser.php">
                        <div class="form-group">
                            <label for="newAdminForeame" class="col-sm-2 control-label">Forename</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="newAdminForename" name="newAdminForename" placeholder="New Admin Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="newAdminSurname" class="col-sm-2 control-label">Surname</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="newAdminSurname" name="newAdminSurname" placeholder="New Admin Surname">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="newUsername" class="col-sm-2 control-label">Username</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="newUsername" name="newUsername" placeholder="New Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="newAdminPassword" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="newAdminPassword" name="newAdminPassword" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="newAdminPasswordCheck" class="col-sm-2 control-label">Enter Password Again</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="newAdminPasswordCheck" name="newAdminPasswordCheck" placeholder="Password">
                            </div>
                        </div>

                        <button class="btn btn-lg btn-primary btn-block" type="submit">Add Admin</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

