<?php require_once 'template/admin_header.phtml';
?>

<?php foreach ($view->productsList as $product) : ?>

    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Product Images for <?= htmlentities($product->getName()); ?> </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <tr>
                                <th>Image ID</th>
                                <th>Image</th>
                                <th>Image Order</th>
                                <th>Action</th>
                            </tr>
                            <?php foreach ($view->productImages as $images) : ?>
                            <form action="admin_productimages.php?prodID=<?= htmlentities($product->getID()); ?>" method="post">    
                            <tr>
                                    
                                    <td><input type="hidden" name="image_id" value="<?php echo htmlentities($images->getImageID()) ?>"</td>
                                    <td><img class="img-square" src="<?php echo htmlentities($images->getProductImages()); ?>" alt="Images" style="height: 200px;">
                                    <td><?php echo htmlentities($images->getImageOrder()) ?></td>
                                    <td><input type="submit" name="delete" class="btn btn-danger" value="delete"></td>
                                </tr>
                            </form>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Add a new Product Image</h3>
                    </div>
                    <div class="panel-body">
                       
<!--                        <form action="<?= $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data">-->
                        <form action="admin_productimages.php?prodID=<?= htmlentities($product->getID()); ?>" method="post" enctype="multipart/form-data">
                            <input type="file" name ="photo" class="btn btn-primary">
                            <input type="submit" name="submit" value="Upload" class="btn btn-success">
                        </form>
                    
                    </div>
                </div>
            </div>
        </div>

    </div>
<?php
endforeach;
