<?php require_once 'template/header.phtml'; ?>

<link href="bootstrap/css/carousel.css" rel="stylesheet">
    
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="images/carousel/Everest_1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to Everest Climbing Supplies.</h1>
              <p></p>
              <p><a class="btn btn-lg btn-primary" href="browse.php" role="button">Browse our Products</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="images/carousel/Everest_2.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>SALE NOW ON!!</h1>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">View Sale Items</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="images/carousel/Thailand_1.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Everest Climbing Supplies.</h1>
              <p>Browse our Gallery.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      
      <?php foreach ($view->categoryDesc as $category) : ?>
      
     
        <div class="col-lg-4">
          <img class="img-square" src="<?php echo htmlentities($category->getImage()); ?>" alt="<?php echo htmlentities($category->getCategory()); ?> Category" style="width: 140px; height: 140px;">
          <h2><?php echo htmlentities($category->getCategory()); ?></h2>
          <p><a class="btn btn-default" href="category.php?cat_id=<?php echo htmlentities($category->getId()); ?>" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 --> 

      <?php endforeach; ?>
      
<!--      <div class="row"> - do we need this row class for each row of 3 columns?-->
      
        
      
       <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; Gareth Hampson - MSc Databases & Web-Based Systems. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->
    
        <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->
  </body>
</html>