
<?php require_once 'template/header.phtml';
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">  
                    <h1>Order Complete</h1>
                    <p> Thank you for your order. The order number is ????? </p>
                    <p>Your Credit Card will be charged ??????</p>
                    <p>An receipt has been sent to your email address.</p>
                    
                </div>
            </div>
        </div>
    </div>
</div>                  