<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>Everest Climbing Supplies</title>

        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="bootstrap/css/navbar-fixed-top.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!--<script src="../../assets/js/ie-emulation-modes-warning.js"></script-->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>

    </head>

    <body>

        <!-- Fixed navbar -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.php">Everest Climbing Supplies</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php">Home</a></li>
                        <li><a href="admin_productlist.php">Admin</a></li>
                        <li><a href="#contact">Contact</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="category.php?cat_id=1">Accessories</a></li>
                                <li><a href="category.php?cat_id=2">Belay Devices</a></li>
                                <li><a href="category.php?cat_id=3">Books</a></li>
                                <li><a href="category.php?cat_id=4">Carabiners</a></li>
                                <li><a href="category.php?cat_id=5">Harnesses</a></li>
                                <li><a href="category.php?cat_id=6">Helmets</a></li>
                                <li><a href="category.php?cat_id=7">Packs</a></li>
                                <li><a href="category.php?cat_id=8">Protection</a></li>
                                <li><a href="category.php?cat_id=9">Quickdraws</a></li>
                                <li><a href="category.php?cat_id=10">Ropes</a></li>
                                <li><a href="category.php?cat_id=11">Shoes</a></li>
                                <li><a href="category.php?cat_id=12">Slings</a></li>
                                
                                <!--<?php foreach ($view->categoryDesc as $category) : ?>

                                    //<li><a href="category.php?cat_id=//<?php echo htmlentities($category->getId()); ?>"><?php echo htmlentities($category->getCategory()); ?></a></li>
                                //<?php endforeach; ?> -->
                                <li class="divider"></li>
                                <li><a href="#">Special Offers</a></li>
                                <li><a href="#">Sales</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">Login</a></li>
                        <li><a href="shoppingcart.php">Shopping Cart</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

